# !-----------------------------------------------------------------------------------------------!
#                       Welcome to the main configuration of VelocityControl
# !-----------------------------------------------------------------------------------------------!
#
#  *IMPORTANT* Ensure you set a unique name for each server in "server.properties" file
#              in your root server folder. The name must be the same as your server name in
#              Velocity config.yml.
#
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# Server name aliases used when broadcasting messages below
# You can edit the sections and remove old keys below.
# Put the server name (see header) as the key, and its alias as the value.
# -------------------------------------------------------------------------------------------------
Server_Aliases: 
  lobby: "hub"

# -------------------------------------------------------------------------------------------------
# Represents settings for player messages such as join, quit and switch messages
# -------------------------------------------------------------------------------------------------
Messages:

  # THIS SECTION IS WORK IN PROGRESS !!
 
  # What aspects of messages should be enabled?
  # Options: JOIN, QUIT, SWITCH
  # >>> CASE SENSITIVE! Must be in capitals otherwise you'll get an error! <<<
  #
  # If you have another plugin handling join/quit etc. messages, remove them from list below.
  # If you want to hide those messages, leave them in Apply_On and empty your messages/ .rs files.
  # >>> CASE SENSITIVE! Must be in capitals otherwise you'll get an error! <<<
  Apply_On: []
  
  # List of server names (see Server_Aliases) that we ignore from broadcasting
  Ignored_Servers:
    - "silent_server"
  
  # Files in messages/ folder are read from top to bottom. A true value means that if you have
  # multiple messages there, we only send the first eligible message to the player (we evaluate
  # this for each player separatedly). A false value means players will see all messages
  # that are eligible for them. 
  Stop_On_First_Match: true
  
  # Automatically append prefix to messages of the given type. Edit/remove/add sections below
  # from Apply_On key above to the left, and prefix to the right.
  # The message types that you do not specify below, will have no prefix unless specified
  # individually. You can also disable prefix for some messages by writing "prefix none" there.
  #
  # Example:
  # Prefix:
  #   join: "&8[&2+&8] &7"
  #   quit: "&8[&4-&8] &7"
  #   kick: "&8[&4-&8] &7"
  #   death: "&8[&4x&8] &7"
  #   timed: "{announce_prefix}"
  Prefix: {}
  
  # If you want to display join message after other plugins, you can send it
  # a bit later such as 1 tick later than the other messages. 
  # **YOU CANNOT OVERRIDE THIS WITH THE "DELAY" OPERATOR**
  Defer_Join_Message_By: 1

# -------------------------------------------------------------------------------------------------
# Intercepting velocity tab commands section - ONLY filters Velocity commands, to filter
# Spigot commands, configure ChatControl on your Spigot server(s).
# -------------------------------------------------------------------------------------------------
Tab_Complete:

  # A map of command labels and their arguments to remove. Put arguments to ["*"] to remove all.
  # Example: This will remove the "survival" tab completion when trying to tab complete /server.
  #
  # Filter_Arguments:
  #   server: [survival]
  #
  Filter_Arguments: {}

# -------------------------------------------------------------------------------------------------
# Chat relay is used for servers that do not have ChatControl installed to forward chat.
# [WARNING] This only forwards chat, no filtering is applied for these servers.
# -------------------------------------------------------------------------------------------------
Chat_Forwarding: 
  
  # Enable this feature?
  Enabled: false

  # List of what servers do not have ChatControl and need chat forwarded to them?
  To_Servers:
    - "minigame1"

  # List of what servers do not have ChatControl and need chat forwarded from them?
  From_Servers:
    - "minigame1"

# -------------------------------------------------------------------------------------------------
# Enable clusters to group your servers into clusters, which limits data transmitted only within
# the same cluster group. Example: You can limit tab-completion to only players on lobbies, etc.
# -------------------------------------------------------------------------------------------------
Clusters:

  # Enable this feature?
  Enabled: false

  # The map of clusters with a list of servers they belong to.
  # Servers not in the list will be placed into a "global" cluster automatically and share data.
  #
  # Example:
  # List:
  #   gameplay:
  #   - factions
  #   - pvp
  #   lobbies:
  #   - hub1
  #   - hub2
  List: {}

# -------------------------------------------------------------------------------------------------
# The format for /spy with proxy commands. Set to "None" to disable completely
# {player_name} = Players username
# {message} = Command that was run
#
# If Spied_Commands is not empty, you will only see commands in that list
# For the example below, you will only see if someone runs /examplecommand
# Spied_Commands:
#   - "examplecommand"
#
# If you want Spied_Commands to be a black list (to ignore a specific commmand) you can do this
# For the example below, you will see all commands BUT /examplecommand
# Spied_Commands:
#   - "@blacklist"
#   - "examplecommand"
#
# -------------------------------------------------------------------------------------------------
Spy:
  Format: "&8[&5Spy&8] &7[&6P&7] &#707070{player_name}: {message}"
  Spied_Commands:

# -------------------------------------------------------------------------------------------------
# Turn on all debug messages
# -------------------------------------------------------------------------------------------------
Debug: false

# -------------------------------------------------------------------------------------------------
# Do not change this value, otherwise it will corrupt your plugin installation!
# -------------------------------------------------------------------------------------------------
